# Stats

In [1]:
#1- if the number of observations is 30 & if the mean is 15, what is sum of all observations

In [2]:
#2- what does measure of variability indicates

In [3]:
#3- what is the range for the following dataset - [12 23 34 54 21 8 9 67]

In [4]:
#4- Calculating the mean,median & mode from the statistics library

In [5]:
#5- Calculate the std & variance using the statstics library

In [66]:
#6- Calculate the mean,median,mode,std,variance without using the library

# Basic Python

In [7]:
# Why do we use ''' (triple quotes)

In [8]:
# Assuming (name = “John Smith”), what does name[1] return?

In [9]:
# What about name[-2]?

In [10]:
# What about name[1:-1]?

In [11]:
# How to get the length of name?

In [12]:
# What are the Escape Sequences in Python?

In [13]:
# Given (name = “john smith”), what will name.title() return?

In [14]:
# What does name.strip() do?

In [15]:
# What will be the value of name after we call name.replace(“j”, “k”)?

In [17]:
# How can we check to see if name contains “John”?

In [18]:
# What are the 3 types of numbers in Python?

In [19]:
# What is the difference between 10 / 3 and 10 // 3?

In [20]:
# Write a function that returns the maximum of two numbers

In [21]:
# Write a function called fizz_buzz that takes a number.
# If the number is divisible by 3, it should return “Fizz”.
# If it is divisible by 5, it should return “Buzz”.
# If it is divisible by both 3 and 5, it should return “FizzBuzz”.
# Otherwise, it should return the same number.

In [22]:
# Write a function for checking the speed of drivers. This function should have one parameter: speed.
# If speed is less than 70, it should print “Ok”.
# Otherwise, for every 5km above the speed limit (70), it should give the driver one demerit point and print the total number of demerit points. For example, if the speed is 80, it should print: “Points: 2”.
# If the driver gets more than 12 points, the function should print: “License suspended”

In [23]:
# Write a function called show_stars(rows). If rows is 5, it should print the following:
#*
#**
#***
#****
#*****

In [24]:
# Write a function that prints all the prime numbers between 0 and a given number

In [25]:
# Accept two int values from the user and return their product. If the product is greater than 1000, then return their sum

In [26]:
# Given (x = 1), what will be the value of after we run (x += 2)?

In [27]:
# How can we round a number? 

In [28]:
# How to get a range of values

In [29]:
# Given a list of numbers, Iterate it and print only those numbers which are divisible of 5

In [1]:
# Return the number of times that the string “Emma” appears anywhere in the given string of times that the string “Emma” appears anywhere in the given string

# Given string is “Emma is a good developer. Emma is also a writer”

# Numpy Exercises

In [1]:
# Import numpy as `np` and print the versio# Import numpy as `np` and print the version number.n number.

In [7]:
# Create a 4X2 integer array and Prints its attributes

#[[64392 31655]
# [32579     0]
# [49248   462]
# [    0     0]]

#1> Array Shape is:  (4, 2)
#2>. Array dimensions are  2
#3>. Length of each element of array in bytes is  2

In [6]:
#  Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

# Creating 5X2 array using numpy.arange
# [[100 110]
# [120 130]
# [140 150]
# [160 170]
# [180 190]]

In [5]:
# Following is the provided numPy array. return array of items in the third column from all rows
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

# expected output
# [[20 39 33]
# [25 25 28]]

# Result array after calculating the square root of all elements
# [[ 400 1521 1089]
# [ 625  625  784]]


In [8]:
# Following is the 2-D array. Print max from axis 0 and min from axis 1
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

# Matplotlib Exercies

In [63]:
# Write a Python programming to display a bar chart of the popularity of programming Languages.

# Programming languages: Java, Python, PHP, JavaScript, C#, C++
# Popularity: 22.2, 17.6, 8.8, 8, 7.7, 6.7

In [64]:
#Write a Python programming to create a pie chart of the popularity of programming Languages.

# Sample data:
# Programming languages: Java, Python, PHP, JavaScript, C#, C++
# Popularity: 22.2, 17.6, 8.8, 8, 7.7, 6.7

In [38]:
# Read Total profit of all months and show it using a line plot on the Sales Dataset

In [36]:
# Show toothpaste Sales Data using a Scatter plot

In [39]:
# Read face cream and facewash product sales data and show it using the bar chart

In [40]:
# Read Bathing soap facewash of all months and display it using the Subplot

# Random

In [65]:
# Generate 3 random integers between 100 and 999 which is divisible by 5

In [42]:
# Pick a random charcter from a given String

In [43]:
# Calculate mutiplication of two random float numbers

In [44]:
# Generate a random date between given start and end dates

# Pandas

In [45]:
# Concatenate these dataframes
# GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
# japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
#

In [46]:
# Merge two data frames using the following condition
# Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
# car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [47]:
# Load the bgg_db Dataset

In [49]:
# Check Description about all columns like count,std,min,max

In [50]:
# Check info about all Columns like datatypes, total size & missing values

In [51]:
# Find the top 5 rows and bottom 5 rows

In [52]:
# First of all, which games are owned by the most people?

In [53]:
# Find the max of all rows

In [2]:
# Filter out all where max players more than 4

In [55]:
# Find the average of each column

In [3]:
# Sort all data by rank column

In [56]:
#  exploring the correlations between variables

In [57]:
# Identify the columns with the high correlations with the rank variable

In [58]:
# Check on all columns if there is any outliers

In [59]:
# Fill if theres any missing values

In [60]:
# Scale, Standardize or normalize the dataset